site_name: 지식정리 Since:26.1.30

theme:
  name: material
  features:
    - content.code.copy
  palette:
    - scheme: default
      primary: blue
      accent: blue
      # 코드 박스/배경을 밝게 보이게 하려면 여기서 선택
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - md_in_html
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.superfences  

nav:
  - Home: index.md
  - User Guide:
      - 테스트1 : 01_PyCom.md
      - 테스트2 : 02_user_guide.md
      - 마크다운 문서예: 03_Markdown_guide.md